version: "3.9"
services:
  sqldb:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: UNO
      MYSQL_DATABASE: uno
      MYSQL_USER: uno
      MYSQL_PASSWORD: uno
    volumes:
      - .:/var/lib/sql/uno
  model:
    container_name: "model-service"
    build:
      context: ./Model
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    stdin_open: true
    tty: true
  persistence:
    container_name: "persistence-service"
    build:
      context: ./Persistence
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_HOST=sqldb:3306
      - MYSQL_USER=uno
      - MYSQL_PASSWORD=uno
    stdin_open: true
    tty: true
  uno:
    container_name: "uno-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - model
      - persistence
    environment:
      - DISPLAY=host.docker.internal:0
      - MODELHTTPSERVER=model-service:8082
      - PERSISTENCEHTTPSERVER=persistence-service:8081